#!/usr/bin/expect

set router  "x.x.x.x"
set username  "user"
set password  "pass"
set port "22"
spawn ssh -p $port  $router
match_max 100000000

set timeout 6

expect "(yes/no)?" {
send "yes\r"; exp_continue }

expect User:
send -- "$username\r"

expect Password:
send -- "$password\r"

expect  >

send -- "terminal lengh 0\r"

send -- "sh run | i snmp\r"

log_file  "show_snmp.txt"

send "logout\r"

expect "(y/N)"
send -- "n\r"

expect eof
